### ISSUE TITLE
iPhone X dock - a bug in landscape mode.

### ISSUE THREAD

**Issue by maxoliinyk** [tomaszpoliszuk/DockController#1]
There is a bug while landscaping mode + iPhone X dock. You can see the icons from the next wall behind the dock. (Right corner on the screenshot)
iPhone 8 plus, IOS 13.5.1
![image](https://user-images.githubusercontent.com/68681586/88583577-1ae36b80-d059-11ea-91b4-52d8b5bbd920.png)

**Comment by tomaszpoliszuk** [comment]
Fixed in eddb6d62d8f80a21a1bc65fc0af28dce1e731d77 (version 2.0.0)
