### ISSUE TITLE
Respring loop in iPad dock when recent applications are disabled

### ISSUE THREAD

**Issue by dinouse** [tomaszpoliszuk/DockController#11]
Im on iphone 6s iOS 14.0 Checkra1n using iPad dock. When i tryna disable recent application it will give me respring loop.

**Comment by tomaszpoliszuk** [comment]
what version of Dock Controller?

**Comment by tomaszpoliszuk** [comment]
Confirmed - I'll create fix as soon as possible.

**Comment by tomaszpoliszuk** [comment]
This issue is now fixed (as of v 1.4.1) but I'll keep it open until version 1.4.1 is published.

Thank you for reporting, have a nice day!

**Comment by tomaszpoliszuk** [comment]
1.4.1 is published - I'm closing this issue :)
