### ISSUE TITLE
iPad Dock controls aren’t shown

### ISSUE THREAD

**Issue by ghost** [tomaszpoliszuk/DockController#12]
I choose the iPad dock setting, and I must say it's pretty great. However, the fact there are three app suggestions making the dock pretty small is annoying. So, I went into iPad dock settings but nothing appeared.

iOS 14.2
Odysseyra1n
iPhone 6s
Dock Controller 1.4.2

![image](https://user-images.githubusercontent.com/65474198/99318447-f76d4800-2824-11eb-8bc9-248078c84141.png)

**Comment by tomaszpoliszuk** [comment]
There is bug in forked preferenceloader you are using.

You'll need preferenceloader from BigBoss repo - http://apt.thebigboss.org/repofiles/cydia/debs2.0/preferenceloader_2.2.5.deb or use alternative preferenceloader made by ArtikusHG, open sourced, available on repo -> https://artikushg.github.io/
