### ISSUE TITLE
2 issues

### ISSUE THREAD

**Issue by stephlol** [tomaszpoliszuk/DockController#13]
-Major issue with HSWidgets, when you unlock your phone, it takes 5 seconds for the icons to appear using ipad dock (not sure if it is the same for the other dock settings as well)

-ipad dock settings is a black page with no options.

Really hope you can fix the hswidgets since it is the best widget tweak out there. Thank you

**Comment by tomaszpoliszuk** [comment]
There is bug in forked preferenceloader you are using.

You'll need preferenceloader from BigBoss repo - http://apt.thebigboss.org/repofiles/cydia/debs2.0/preferenceloader_2.2.5.deb or use alternative preferenceloader made by ArtikusHG, open sourced, available on repo -> https://artikushg.github.io/

Do that and turn off layout fix inside - then check if issue with HSWidgets is still present.

**Comment by tomaszpoliszuk** [comment]
@stephlol Is issue still persist?

**Comment by stephlol** [comment]
> @stephlol Is issue still persist?

Yes it is

**Comment by tomaszpoliszuk** [comment]
Just to make sure - you've fixed issue with preferenceloader and turned off layout fix inside iPad dock settings?

**Comment by stephlol** [comment]
> Just to make sure - you've fixed issue with preferenceloader and turned off layout fix inside iPad dock settings?

Yes it works fine with fix off. But that leaves no room for widgets

**Comment by tomaszpoliszuk** [comment]
Ok, thank you - i will see what i can do with it :)

**Comment by stephlol** [comment]
> Ok, thank you - i will see what i can do with it :)

Thanks a ton. Really appreciate your work

**Comment by stephlol** [comment]
> Ok, thank you - i will see what i can do with it :)

Still not working with the new update. Just to let you know

**Comment by tomaszpoliszuk** [comment]
I'm aware of that (it was addressing issue #14) - I suspect what I need to change in this one but don't know (yet) how (need more research)

**Comment by tomaszpoliszuk** [comment]
I'll let you know as soon as I find fix

**Comment by tomaszpoliszuk** [comment]
Could you download and check [this testing version](http://tomaszpoliszuk.com/files/jailbreak/testing/com.tomaszpoliszuk.dockcontroller_1.4.3-2%2Bdebug_iphoneos-arm.deb)?
It's deb file to install manually using for example Filza.

**Comment by stephlol** [comment]
> Could you download and check [this testing version](http://tomaszpoliszuk.com/files/jailbreak/testing/com.tomaszpoliszuk.dockcontroller_1.4.3-2%2Bdebug_iphoneos-arm.deb)?
> 
> It's deb file to install manually using for example Filza.

Works with the fix on but leaves little room for the widgets.

**Comment by tomaszpoliszuk** [comment]
Could you send me screenshot so I could better understand nature of this issue?

**Comment by stephlol** [comment]
> Could you send me screenshot so I could better understand nature of this issue?

![image](https://user-images.githubusercontent.com/69172252/101674642-9bee3e80-3a0d-11eb-92b6-d14e37eb781e.png)

Usually there are two rows at the bottom. This only leaves one leaving little room to put widgets across the pages.

**Comment by tomaszpoliszuk** [comment]
Correct me if I'm wrong but AFAIK springboard have only 6 rows of icons so everything seems correct - does it?

**Comment by tomaszpoliszuk** [comment]
I'm closing this issue due to lack of contact.
