### ISSUE TITLE
Rounded dock bug 

### ISSUE THREAD

**Issue by joseclark95** [tomaszpoliszuk/DockController#14]
Hi, I’ve found a bug on iOS 14.1, the tweak worked fine in 13.5.

When using the rounded dock type the dock form isn’t the correct one and it reaches the edges of the screen. 

iPhone 7 iOS 14.1

![9D1D2ACF-99B7-498E-BE7F-A3B544C61794](https://user-images.githubusercontent.com/61067053/100185493-3b092700-2ea1-11eb-934b-428cf31a1308.png)

**Comment by tomaszpoliszuk** [comment]
Thanks for reporting - I'll look into it soon.

**Comment by tomaszpoliszuk** [comment]
I've fixed this one few minutes ago (and additional bug i've discovered) - I'll test it tomorrow once again and if everything will be correct I'll send update to BigBoss repo.

Have a nice day!

**Comment by joseclark95** [comment]
Sweet, thank you very much, I'll be waiting.

Have a nice day too!

**Comment by tomaszpoliszuk** [comment]
I've updated code on GitHub and sent version 1.4.3 to BigBoss repo - I'm not sure if it will be included in today repo update or little later but i've included deb file on [releases](https://github.com/tomaszpoliszuk/DockController/releases) page of tweak so you can download and install it from deb file (using for example Filza) and use right now or you can wait until it will be published on BigBoss.

Have a nice day!

**Comment by joseclark95** [comment]
Thanks, this fixes the issue!
