### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by CySxL** [tomaszpoliszuk/DockController#15]
1. Add ability to display running indicator as little white/black dots under those apps in dock which are running in background. (Recent apps as well)

And let users choose themself which color of running indicator dots they want in system Light/Dark mode. 

For instant: white dots in Dark mode and black dots in Light mode, or just using black dots in both mode... etc.
(Btw, Harbor3 has this feature and it's open source now, would be great if you can take a look on it :)  )

2. White Dock Divider in system Dark mode.

3. customize FIX ICONS LAYOUT ON SPRINGBOARD for Portrait orientation value 

4. support of Activator listener of "Drag up from XXX app" in iPad dock.

Workaround of mine: Placing Safari in dock and wanna use Activator listener of "Drag up from Safari" to invoke event "Open new tab". But seems not working while Dock Controller is installed and choosing iPad Dock Style.

**Comment by tomaszpoliszuk** [comment]
Could you please split this one into separate issues?

I'll address them as soon as possible.

**Comment by CySxL** [comment]
Sure ! Sorry for that. Into 4 issues right ?

**Comment by tomaszpoliszuk** [comment]
Yeah - it will be great!

**Comment by CySxL** [comment]
Done !!

**Comment by tomaszpoliszuk** [comment]
Awesome - I'm closing this one and we will continue in that separate issues.

Have a nice day!
