### ISSUE TITLE
iPad style will pull down Page Dots.

### ISSUE THREAD

**Issue by italoboy** [tomaszpoliszuk/DockController#19]
This is a bad bug, please fix it and separate page dots from dock or iPad mode style.

Tnx

**Comment by tomaszpoliszuk** [comment]
It's not that bad (doesn't crash device) but Yeah - i will look into it.

**Comment by davidiesel** [comment]
Please bro provide a fix

**Comment by tomaszpoliszuk** [comment]
Hi, is "Additional Bottom Spacing" fixes that issue for you?

**Comment by tomaszpoliszuk** [comment]
Closed due to lack of replies.
