### ISSUE TITLE
Vinculum 2 Support

### ISSUE THREAD

**Issue by alxndrdaemon** [tomaszpoliszuk/DockController#23]
Hi how are u?, Excuse me, i wonder if you could add Vinculum support please. Thx

**Comment by tomaszpoliszuk** [comment]
What's not working and with what settings?

**Comment by alxndrdaemon** [comment]
https://user-images.githubusercontent.com/66810492/118639592-b20ee080-b79d-11eb-8d9d-a66af45c77c8.MOV

**Comment by alxndrdaemon** [comment]
Default option work perfectly, just with iPad Style doesn't work.> What's not working and with what settings?

**Comment by tomaszpoliszuk** [comment]
So it means that iPad Dock is not supported in Vinculum (so it also won't work on iPads), you'll have to ask Vinculum developer to add compatibility to iPad docks.
