### ISSUE TITLE
iPhone dock option results in respring loop with iPhone 7

### ISSUE THREAD

**Issue by burakdede0** [tomaszpoliszuk/DockController#25]
After the 2.0.0 update, the preferences are reset. iPad dock options work fine but choosing the iPhone dock and respringing results in respring loop.

iPhone 7
iOS 15.7.5
palera1n Rootless

No other dock tweaks installed

What I’ve tried:
- Reinstalling the tweak

**Comment by tomaszpoliszuk** [comment]
Thank you for reporting, I'll debug it later today.

**Comment by tomaszpoliszuk** [comment]
Fixed in ca184c6d5165715fc22a947a2fd1e34cad9afc20, please use deb files from [2.0.1](https://github.com/tomaszpoliszuk/DockController/releases/tag/2.0.1) until package is updated on BigBoss

**Comment by burakdede0** [comment]
Thanks for the quick fix. It works. But the rounded iPhone dock for non-notched devices seems to be gone now.

**Comment by tomaszpoliszuk** [comment]
Yes, rounded/square dock options are gone, they'll be back as different settings - just for iPhone Dock as soon as I fix all bugs I've noticed so far in that new options.

**Comment by tomaszpoliszuk** [comment]
It's published on BigBoss
