### ISSUE TITLE
Cannot dismiss Lock Screen

### ISSUE THREAD

**Issue by burkybang** [tomaszpoliszuk/DockController#26]
v2.0.1

It doesn't let me dismiss the Lock Screen. If I swipe up from the bottom of the screen, it scrolls my notifications.

My workaround is to activate Control Center and open a shortcut to an app like Calculator for example. Then I can exit the app to get to the Home Screen.

**Comment by tomaszpoliszuk** [comment]
Could you check deb from this [Archive.zip](https://github.com/tomaszpoliszuk/DockController/files/11737724/Archive.zip) (com.tomaszpoliszuk.dockcontroller_2.0.1-5+debug_iphoneos-arm.deb for regular jailbreak, com.tomaszpoliszuk.dockcontroller_2.0.1-6+debug_iphoneos-arm64.deb for rootless).

**Comment by burkybang** [comment]
That has resolved the issue where I cannot dismiss the Lock Screen. However, now I have a new issue where I can't exit apps. Swiping up from the bottom does not dismiss an app and take me back to the Home Screen.

**Comment by tomaszpoliszuk** [comment]
What about this [Archive.zip](https://github.com/tomaszpoliszuk/DockController/files/11737797/Archive.zip)
-7 for regular, -8 for rootless.
Please check with "Gesture to show Dock in Apps" enabled & disabled (respring between changes is required).

**Comment by Triple-999** [comment]
I was also experiencing the same issues for rootless. I can confirm the rootless page seems to have fixed the issue for me at least.

**Comment by tomaszpoliszuk** [comment]
Just published [2.0.2](https://github.com/tomaszpoliszuk/DockController/releases/tag/2.0.2) with above fix, please verify.
If confirmed I'll send it to BigBoss.

**Comment by burkybang** [comment]
Can confirm. v2.0.2 does resolve it. Thanks!

**Comment by tomaszpoliszuk** [comment]
Awesome, thank you for confirming, 2.0.2 will be available from repo soon.
