### ISSUE TITLE
v2.0.2 breaks bottom row of icons for every page on Home Screen

### ISSUE THREAD

**Issue by badger200** [tomaszpoliszuk/DockController#27]
Just upgraded from 1.63 or whatever it was, to 2.0.2 and it bizarrely moved the bottom row 4 apps of each page, to a new page adjacent to the previous, with just those 4 apps. 

Now I have twice as many Home Screen app pages as I did before. Luckily when I rebooted it restored them normal.

iPhone 6
iOS 12.4
Unc0ver 6.2.0

**Comment by tomaszpoliszuk** [comment]
Please provide more info:
* what settings are applied?
* how many rows of apps do you expect vs how many you have?
* do you have any tweak installed that modifies homescreen? (if so, what happen if you disable it?)

**Comment by tomaszpoliszuk** [comment]
Probably fixed in 2.1, hard to tell without replies.
