### ISSUE TITLE
Need old releases available to Downgrade in Cydia

### ISSUE THREAD

**Issue by badger200** [tomaszpoliszuk/DockController#28]
In Cydia I cannot Downgrade to last known good 1.6.2 because only 2.0.2 is available. Please add old version debs.

**Comment by tomaszpoliszuk** [comment]
It's not a problem with tweak.
I don't have control over repo so I can't add older versions (I will consider creating my own repo with archive of previous versions).
1.6.2 can be downloaded from [here](http://apt.thebigboss.org/repofiles/cydia/debs2.0/dockcontroller_1.6.2.deb) if needed 🙂
