### ISSUE TITLE
Disable iPad dock from switcher page

### ISSUE THREAD

**Issue by tomaszpoliszuk** [tomaszpoliszuk/DockController#5]
Requested [here](https://old.reddit.com/r/jailbreak/comments/i0ntaj/update_open_source_dock_controller_control_your/fzrm6y8/)

**Comment by CySxL** [comment]
Instead of removing it, please make an option for users to choose. I'm SO in love with the ipad dock in switcher, that's the main reason i use Dock Controller.  😢

**Comment by tomaszpoliszuk** [comment]
Oh totally - it will be option to choose :)

**Comment by CySxL** [comment]
Appreciate!!! 🥰🥰

**Comment by tomaszpoliszuk** [comment]
It is now an option in version 1.5 - enjoy!

**Comment by CySxL** [comment]
Saw it ! Thanks :)
