### ISSUE TITLE
Ability to change settings dynamically (without respring)

### ISSUE THREAD

**Issue by tomaszpoliszuk** [tomaszpoliszuk/DockController#9]
It would also make possible to dynamically change icon layout on springboard (it would remove whitespace between springboard and dock when there are more than 4 icons in iPad Dock).

Additional discussion about this issue can be found [here](https://github.com/tomaszpoliszuk/AppSwitcherController/issues/1#issuecomment-679255597).

**Comment by alxndrdaemon** [comment]
That's it.

**Comment by tomaszpoliszuk** [comment]
For some options it's already made, for rest, like changing number of recent items or dock type it's just too much work.
